/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    repositories {
        mavenCentral()
        google()
    }
    plugins {
        id("java")
    }
}
rootProject.name = "gradle-tutorial"
include("app")
include("gralde-java-sample")
include("scripts")

buildscript {
    buildCache {
        local {
            directory = File(rootDir, "build-cache")
        }
    }
}
